name: golang-full

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS
    strategy:
      matrix:
        go-version: [1.12, 1.15]
        os: [macOS-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          node-version: ${{ matrix.go-version }}
      - name: Test
        run: go test -v ./...
      - name: Build
        run: go build -v ./...